name: frontend
description: A new Flutter app project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.1.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.0
  flutter_slidable: ^2.0.0
  carousel_slider: ^4.1.1
  url_strategy: ^0.2.0
  camera: ^0.10.0+3
  shared_preferences: ^2.0.13
  just_audio: ^0.9.21
  video_player: ^2.4.7
  better_player: ^0.0.82
  flutter_staggered_grid_view: ^0.6.1
  font_awesome_flutter: ^10.1.0
  responsive_builder: ^0.4.2
  lazy_loading_list: ^1.0.1
  http: ^0.13.4
  email_validator: ^2.0.1
  share_plus: ^5.0.0
  flutter_dotenv: ^5.0.2
  file_picker: ^3.0.0
  #  client_information: ^2.0.2+2
  permission_handler: 9.2.0
  path_provider: ^2.0.11
  provider: ^6.0.5
  images_picker: ^1.2.11
  image_picker: ^0.8.6
  photo_manager: ^2.4.1
  photofilters: ^3.0.1
  uuid: ^3.0.7
  rxdart: ^0.27.7
  chewie: ^1.3.6
  mime: ^1.0.4
  video_thumbnail: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - .env.dev
    - .env.prod
    - assets/
    - assets/media/images/
    - assets/media/images/user/
